### PR TITLE
update to nushell 0.84.1 + new record api

### PR DESCRIPTION
**Pull request by fdncred**
This PR updates the plugin to use the new [record api](https://github.com/nushell/nushell/pull/10103) and the latest nushell. I realize you might not accept this because it's pointing to a development version of nushell but just wanted to pass the info along.

### CODE REVIEW

**Comment by JosephTLyons** [comment]
Hey thanks @fdncred, really appreciate you opening this up. I'll check this PR out over this weekend.

**Comment by JosephTLyons** [comment]
Thanks for the information about the record api and for the PR here, I think what I will do is leave it open until those dependencies are published, then bump them in the PR and merge this then :).

**Comment by fdncred** [comment]
Sounds good. I haven't looked at your plugin, but I believe there are other changes need now too. We're breaking more things. Getting ready to make some significant span changes.

**Comment by JosephTLyons** [comment]
Seems like all of this is stable now, anything else I should consider pulling into this PR @fdncred?

**Comment by JosephTLyons** [comment]
I'm seeing this error on the newest versions of things (0.85.0) - should I be using `internal_span`?

SCR-20231013-nane

**Comment by fdncred** [comment]
yup, that's right. You can't do that any longer. We've made some fairly significant breaking changes back to back. The solution for that is to do something like this `return Ok(Value::nothing(span));`

**Comment by JosephTLyons** [comment]
Oh, so I shouldn't be using `internal_span`?

**Comment by JosephTLyons** [comment]
Oh I see, there are methods now to build these things:

`Value::string(element.get_standard_state().name().to_string(), *tag)`

**Comment by fdncred** [comment]
yup, that's right. we started making changes to reduce spans in nushell, but we haven't finished yet. that's why we've made this change.

**Comment by JosephTLyons** [comment]
Thanks, appreciate the help here :)

**Pull request merged**
